name: whisp
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^3.6.0 
  firebase_auth: ^5.3.1 
  cloud_firestore: ^5.4.4 
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0
  image: ^4.3.0
  async: ^2.11.0
  flutter_launcher_icons: ^0.14.1
  


flutter:
  assets:
    - assets/welcome_screen.png
    - assets/ic_whispicon.png
    - assets/login_screen.png
    - assets/profile_placeholder.png
    - assets/search_image.png
    - assets/whisp_icon.png
  
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/whisp_icon.png" 
image_path_android_round: "assets/whisp_icon.png"
  
